// Generated by LiveScript 1.3.0
(function(){
  var fs, pug, path, cwd;
  fs = require('fs');
  pug = require('../build/pug');
  path = require('path');
  cwd = path.resolve(process.cwd());
  module.exports = {
    build: function(list){
      var t1, src, des, mods, fn, ret;
      if (list.filter(function(it){
        return !!/src\/pug\/spinner\/index.pug$/.exec(it);
      }).length) {
        t1 = Date.now();
        src = "src/pug/spinner/index.pug";
        des = "static/spinner/index.html";
        mods = fs.readdirSync('static/mod/spinner/').filter(function(it){
          return fs.existsSync("static/mod/spinner/" + it + "/meta.json");
        }).map(function(it){
          return JSON.parse(fs.readFileSync("static/mod/spinner/" + it + "/meta.json").toString());
        }).filter(function(it){
          return !it.debug;
        });
        fn = pug.compile(src, {});
        ret = fn({
          mods: mods
        });
        fs.writeFileSync(des, ret);
        return console.log("[BUILD] " + src + " --> " + des + " ( " + (Date.now() - t1) + "ms )");
      }
    },
    unlink: function(){}
  };
}).call(this);
