from: '"#{teamname} Support" <noreply@#{domain}>'
subject: '電子郵件信箱認證 / #{domain}'
content: |
  您好！

  您會收到這封信是因為有人在 #{domain} 使用了您的電子郵件註冊，並發出了認證信件的要求。若您並沒有在 #{domain} 註冊，請直接忽略此信，或者您亦可直接回覆此信來要求移除此帳號。

  若要認證您的電子郵件信箱，請開啟以下連結：

  [https://#{domain}/dash/me/mail/verify/#{token}](https://#{domain}/dash/me/mail/verify/#{token})

  此封郵件由系統自動生成，請勿直接回信，以免您的訊息無人接收。感謝！
  #{teamname} 團隊
