from: '"#{displayname} Support" <noreply@#{domain}>'
subject: Email Verification from #{domain}
content: |
  You receive this mail because there is an email verification request for the account using this email in #{domain}. If you didn't sign up #{domain}, please just ignore this mail, or reply directly to ask removing email.

  To verify your email, click following link:

  [https://#{domain}/me/mail/verify/#{token}](https://#{domain}/me/mail/verify/#{token})

  Thanks,
  #{domain} team
