from: '"Battle Dash Support" <contact@battledash.io>'
subject: Email Verification from battledash.io
content: |
  You receive this mail because there is an email verification request for the account using this email in xinmeti.co. If you didn't sign up xinmeti.co, please just ignore this mail, or reply directly to ask removing email.

  To verify your email, click following link:

  [https://battledash.io/me/mail/verify/#{token}](https://battledash.io/me/mail/verify/#{token})

  Thanks,
  battledash.io team
