from: '"#{displayname} Support" <noreply@#{domain}>'
subject: Password Reset from #{domain}
content: |
  You receive this mail because there is a password reset request for the account using this email in #{domain}. If you didn't ask for password reset, please just ignore this mail.

  To reset your password, click following link:

  [https://#{domain}/me/passwd/reset/#{token}](https://#{domain}/me/passwd/reset/#{token})

  Thanks,
  #{domain} team
