from: '"battledash.io Support" <noreply@battledash.io>'
subject: Password Reset from battledash.io
content: |
  You receive this mail because there is a password reset request for the account using this email in battledash.io. If you didn't ask for password reset, please just ignore this mail.

  To reset your password, click following link:

  [https://battledash.io/me/passwd/reset/#{token}](https://battledash.io/me/passwd/reset/#{token})

  Thanks,
  battledash.io team
