// Generated by LiveScript 1.3.0
(function(){
  var crypto, lderror, mail, verifyEmail;
  crypto = require('crypto');
  lderror = require('lderror');
  mail = require('./mail');
  verifyEmail = function(arg$){
    var req, io, user, obj;
    req = arg$.req, io = arg$.io, user = arg$.user;
    obj = {};
    return Promise.resolve().then(function(){
      var time;
      time = new Date();
      obj.key = user.key;
      obj.hex = (user.key + "-") + crypto.randomBytes(30).toString('hex');
      obj.time = time;
      return io.query("delete from mailverifytoken where owner=$1", [obj.key]);
    }).then(function(){
      return io.query("insert into mailverifytoken (owner,token,time) values ($1,$2,$3)", [obj.key, obj.hex, obj.time]);
    }).then(function(){
      var ref$, ref1$;
      return mail.byTemplate('mail-verify', user.username, (ref1$ = {
        token: obj.hex,
        domain: 'grantdash.io',
        orgname: 'Grant Dash'
      }, ref1$.domain = (ref$ = req.scope).domain, ref1$.orgname = ref$.orgname, ref1$), {
        now: true
      });
    });
  };
  module.exports = {
    verifyEmail: verifyEmail
  };
}).call(this);
