// Generated by LiveScript 1.3.0
(function(){
  var fs, path, lderror, aux;
  fs = require('fs');
  path = require('path');
  lderror = require('lderror');
  aux = require('../aux');
  (function(it){
    return module.exports = it;
  })(function(engine, io){
    var api;
    api = engine.router.api;
    return api.post('/toc', aux.signed, function(req, res){
      var hint, ref$, lc, promise;
      hint = {
        org: (ref$ = req.body).org,
        brd: ref$.brd
      };
      lc = {};
      promise = hint.brd
        ? io.query("select * from brd where slug = $1", [hint.brd]).then(function(r){
          r == null && (r = {});
          if (!(lc.brd = (r.rows || (r.rows = []))[0])) {
            return aux.reject(404);
          }
          return io.query("select key,name,slug,description,detail from org where slug = $1", [lc.brd.org]);
        }).then(function(r){
          r == null && (r = {});
          return lc.org = (r.rows || (r.rows = []))[0] || null;
        })
        : hint.org
          ? io.query("select * from org where slug = $1", [hint.org]).then(function(r){
            r == null && (r = {});
            if (!(lc.org = (r.rows || (r.rows = []))[0])) {
              return aux.reject(404);
            }
          })
          : io.query("select * from brd where owner = $1 order by createdtime desc limit 1", [req.user.key]).then(function(r){
            r == null && (r = {});
            if (!(lc.brd = (r.rows || (r.rows = []))[0])) {
              return io.query("select * from org where owner = $1 order by createdtime limit 1", [req.user.key]).then(function(r){
                r == null && (r = {});
                if (!(lc.org = (r.rows || (r.rows = []))[0])) {
                  return aux.reject(404);
                }
              });
            } else {
              return io.query("select * from org where slug = $1", [lc.brd.org]);
            }
          }).then(function(r){
            r == null && (r = {});
            return lc.org = (r.rows || (r.rows = []))[0] || null;
          }).then(function(){
            if (!(lc.brd || lc.org)) {
              return aux.reject(404);
            }
          });
      return promise.then(function(){
        if (!lc.org) {
          return io.query("select * from brd where org is null");
        } else {
          return io.query("select * from brd where org = $1", [lc.org.slug]);
        }
      }).then(function(r){
        r == null && (r = {});
        lc.brds = r.rows || (r.rows = []);
        return res.send(lc);
      })['catch'](aux.errorHandler(res));
    });
  });
}).call(this);
