// Generated by LiveScript 1.3.0
(function(){
  var fs, path;
  fs = require('fs');
  path = require('path');
  (function(it){
    return module.exports = it;
  })(function(engine, io){
    var api;
    api = engine.router.api;
    api.get('/comments/:id', function(req, res){});
    api.post('/comment/', function(req, res){});
    api.put('/comment/:id', function(req, res){});
    return api['delete']('/comment/:id', function(req, res){});
  });
}).call(this);
