// Generated by LiveScript 1.3.0
(function(){
  var fs, fsExtra, path, crypto, lderror, suuid, mimeTypes, aux, cache, common, grecaptcha, throttle, storage;
  fs = require('fs');
  fsExtra = require('fs-extra');
  path = require('path');
  crypto = require('crypto');
  lderror = require('lderror');
  suuid = require('suuid');
  mimeTypes = require('mime-types');
  suuid = require('suuid');
  aux = require('../aux');
  cache = require('./cache');
  common = require('./common');
  grecaptcha = require('../util/grecaptcha');
  throttle = require('../util/throttle');
  storage = require('@google-cloud/storage');
  storage = new storage.Storage({
    projectId: 'taicca',
    keyFilename: 'config/key/taicca.json'
  });
  (function(it){
    return module.exports = it;
  })(function(engine, io){
    var api, app;
    api = engine.router.api;
    app = engine.app;
    api.post('/flagship/upload', function(req, res){
      var filename, id;
      filename = req.body.filename;
      id = suuid();
      return storage.bucket('taicca-test').file(id).getSignedUrl({
        action: 'write',
        version: 'v4',
        expires: Date.now() + 60000
      }).then(function(it){
        return res.send({
          signedUrl: it[0],
          id: id
        });
      })['catch'](aux.errorHandler(res));
    });
    return app.get('/flagship/upload/:id', function(req, res){
      var id;
      id = req.params.id;
      return storage.bucket('taicca-test').file(id).getSignedUrl({
        action: 'read',
        version: 'v4',
        expires: Date.now() + 60000
      }).then(function(it){
        return res.status(302).redirect(it[0]);
      })['catch'](aux.errorHandler(res));
    });
  });
}).call(this);
