// Generated by LiveScript 1.3.0
(function(){
  var fs, path, admin, user, prj, brd, org, judge, perm, discuss, post, form, reset, verify;
  fs = require('fs');
  path = require('path');
  admin = require('./admin');
  user = require('./user');
  prj = require('./prj');
  brd = require('./brd');
  org = require('./org');
  judge = require('./judge');
  perm = require('./perm');
  discuss = require('./discuss');
  post = require('./post');
  form = require('./form');
  reset = require('./auth/reset');
  verify = require('./auth/verify');
  module.exports = function(engine, io){
    var flagship, e;
    user(engine, io);
    reset(engine, io);
    verify(engine, io);
    brd(engine, io);
    org(engine, io);
    judge(engine, io);
    discuss(engine, io);
    admin(engine, io);
    prj(engine, io);
    post(engine, io);
    perm(engine, io);
    form(engine, io);
    try {
      flagship = require('./flagship');
    } catch (e$) {
      e = e$;
      console.log(e);
    }
    if (flagship != null) {
      return flagship(engine, io);
    }
  };
}).call(this);
