// Generated by LiveScript 1.3.0
(function(){
  var fs, aux;
  fs = require('fs');
  aux = require('../aux');
  (function(it){
    return module.exports = it;
  })(function(engine, io){
    var app;
    app = engine.app;
    return app.get('/doc/create', aux.needlogin(function(req, res){
      if (!(req.user || (req.user = {})).key) {
        return aux.r403(res);
      }
      return io.query("select count(key) as count from doc where deleted is not true and owner = $1", [req.user.key]).then(function(r){
        var count;
        r == null && (r = {});
        count = ((r.rows || (r.rows = []))[0] || {}).count || 0;
        if (count >= 200) {
          return aux.reject(403);
        }
        return io.query("insert into doc (owner) values ($1) returning key", [req.user.key]);
      }).then(function(r){
        var key, docId, doc;
        r == null && (r = {});
        if (!(key = ((r.rows || (r.rows = []))[0] || {}).key)) {
          aux.reject(403);
        }
        docId = req.user.key + "-" + key;
        doc = engine.sharedb.connect.get('doc', docId);
        return new Promise(function(resolve, rej){
          return doc.create({}, function(e){
            if (e) {
              return rej(new Error(e));
            } else {
              return resolve(res.redirect("/doc/" + docId));
            }
          });
        });
      })['catch'](function(it){
        return console.log(it);
      });
    }));
  });
}).call(this);
