// Generated by LiveScript 1.3.0
(function(){
  var fs, fsExtra, path, crypto, readChunk, sharp, expressFormidable, uploadr, lderror, suuid, aux, cache;
  fs = require('fs');
  fsExtra = require('fs-extra');
  path = require('path');
  crypto = require('crypto');
  readChunk = require('read-chunk');
  sharp = require('sharp');
  expressFormidable = require('express-formidable');
  uploadr = require('uploadr');
  lderror = require('lderror');
  suuid = require('suuid');
  aux = require('../aux');
  cache = require('./cache');
  (function(it){
    return module.exports = it;
  })(function(engine, io){
    var api, app;
    api = engine.router.api;
    app = engine.app;
    api.post('/account', aux.signed, function(req, res){
      var name;
      if (!(name = req.body.name)) {
        return aux.r404(res);
      }
      name = (name + "").substring(0, 32);
      return io.query("select key,displayname from users where lower(displayname) ~ lower($1)", [name]).then(function(r){
        r == null && (r = {});
        return res.send(r.rows || (r.rows = []));
      })['catch'](aux.errorHandler(res));
    });
    return api.get('/stage', function(req, res){
      var brd;
      brd = {
        brd: req.query.brd
      }.brd;
      if (!brd) {
        return aux.r400(res);
      }
      return cache.stage.check({
        io: io,
        type: 'brd',
        slug: brd
      }).then(function(it){
        return res.send(it);
      })['catch'](aux.errorHandler(res));
    });
  });
}).call(this);
