// Generated by LiveScript 1.3.0
(function(){
  var request, aux, secret, lderror;
  request = require('request');
  aux = require('../../aux');
  secret = require('../../../secret');
  lderror = require('lderror');
  module.exports = function(req, res, next){
    if (!(secret.grecaptcha && secret.grecaptcha.enabled)) {
      return next();
    }
    return request({
      url: 'https://www.google.com/recaptcha/api/siteverify',
      method: 'POST',
      form: {
        secret: secret.grecaptcha.secret,
        response: req.body.recaptcha,
        remoteip: aux.ip(req)
      }
    }, function(e, r, b){
      var data;
      if (e) {
        return next(new lderror(1010));
      }
      try {
        data = JSON.parse(b);
      } catch (e$) {
        e = e$;
        return next(new lderror(1010));
      }
      if (data.success === false) {
        return next(new lderror(1009));
      }
      if (!data.score || data.score < 0.5) {
        return next(new lderror(1009));
      }
      req.recaptcha = data;
      return next();
    });
  };
}).call(this);
