// Generated by LiveScript 1.3.0
(function(){
  var fs, colors, jsYaml, nodemailer, nodemailerMailgunTransport, md, aux, secret, mailgun, mailQueue;
  fs = require('fs');
  colors = require('colors');
  jsYaml = require('js-yaml');
  nodemailer = require('nodemailer');
  nodemailerMailgunTransport = require('nodemailer-mailgun-transport');
  md = require('./md');
  aux = require('../../aux');
  secret = require('../../../secret');
  mailgun = nodemailer.createTransport(nodemailerMailgunTransport(secret.mailgun));
  mailQueue = {
    list: [],
    add: function(obj){
      this.list.push(obj);
      return this.handler();
    },
    handle: null,
    handler: function(){
      var this$ = this;
      if (this.handle) {
        return;
      }
      console.log("[MAIL-QUEUE] new job incoming, handling...".cyan);
      return this.handle = setInterval(function(){
        var obj;
        console.log(("[MAIL-QUEUE] " + this$.list.length + " jobs remain...").cyan);
        obj = this$.list.splice(0, 1)[0];
        if (!obj) {
          console.log("[MAIL-QUEUE] all job done, take a rest.".green);
          clearInterval(this$.handle);
          this$.handle = null;
          return;
        }
        return module.exports.sendDirectly(obj.payload).then(obj.res)['catch'](obj.rej);
      }, 5000);
    }
  };
  module.exports = {
    send: function(payload, opt){
      opt == null && (opt = {});
      if (opt.now) {
        return module.exports.sendDirectly(payload);
      }
      return new Promise(function(res, rej){
        return mailQueue.add({
          payload: payload,
          res: res,
          rej: rej
        });
      });
    },
    sendDirectly: function(payload){
      return new Promise(function(res, rej){
        console.log(("[MAILGUN] sending [from:" + payload.from + "] [to:" + payload.to + "] [subject:" + payload.subject + "]").cyan);
        return mailgun.sendMail(payload, function(e, i){
          if (!e) {
            return res();
          }
          console.log("[MAILGUN] SendMail failed: ".red, e);
          return rej(aux.error(500, "failed to send mail. try later?"));
        });
      });
    },
    sendFromMd: function(payload, map, opt){
      map == null && (map = {});
      opt == null && (opt = {});
      return new Promise(function(res, rej){
        var content, k, ref$, v;
        content = payload.content || '';
        for (k in ref$ = map) {
          v = ref$[k];
          content = content.replace(new RegExp("#{" + k + "}", "g"), v);
        }
        payload.text = md.toText(content);
        payload.html = md.toHtml(content);
        delete payload.content;
        return module.exports.send(payload, opt).then(function(){
          return res();
        });
      });
    },
    byTemplate: function(name, email, map, config){
      map == null && (map = {});
      config == null && (config = {});
      return new Promise(function(res, rej){
        var path, that;
        path = (that = config.path) ? that : '.';
        return fs.readFile(path + "/config/mail/" + name + ".yaml", function(e, content){
          var payload, option;
          if (e) {
            console.log("[MAIL] send mail failed: ", e);
            return rej(aux.error(500, "failed to send mail. try later?"));
          }
          try {
            payload = jsYaml.safeLoad(content);
          } catch (e$) {
            e = e$;
            console.log("[MAIL] send mail failed: ", e);
            return rej(aux.error(500, "failed to send mail. try later?"));
          }
          option = {
            from: payload.from,
            to: email,
            subject: payload.subject,
            content: payload.content
          };
          if (config.bcc) {
            option.bcc = config.bcc;
          }
          return module.exports.sendFromMd(option, map, {
            now: config.now
          }).then(function(){
            return res();
          })['catch'](function(e){
            return rej(e);
          });
        });
      });
    }
  };
}).call(this);
