// Generated by LiveScript 1.3.0
(function(){
  var fs, fsExtra, crypto, expressRateLimit, lderror, aux, throttle, mail, action;
  fs = require('fs');
  fsExtra = require('fs-extra');
  crypto = require('crypto');
  expressRateLimit = require('express-rate-limit');
  lderror = require('lderror');
  aux = require('../../aux');
  throttle = require('../../util/throttle');
  mail = require('../../util/mail');
  action = require('../../util/action');
  (function(it){
    return module.exports = it;
  })(function(engine, io){
    engine.router.api.post('/me/mail/verify', throttle.count.action.mail, function(req, res){
      var obj;
      obj = {};
      if (!(req.user && req.user.key && req.user.username)) {
        return aux.r400(res, "not login.");
      }
      return io.query("select key from users where key = $1 and deleted is not true", [req.user.key]).then(function(r){
        r == null && (r = {});
        if (!(r.rows || (r.rows = [])).length) {
          return aux.reject(404);
        }
        return action.verifyEmail({
          req: req,
          user: req.user,
          io: io
        });
      }).then(function(){
        return res.send();
      })['catch'](aux.errorHandler(res, true));
    });
    return engine.app.get('/me/mail/verify/:token', throttle.count.ipMd, function(req, res){
      var lc, token;
      lc = {};
      token = req.params.token;
      if (!token) {
        return aux.r400(res, "", true);
      }
      return io.query("select owner,time from mailverifytoken where token = $1", [token]).then(function(r){
        var obj;
        r == null && (r = {});
        if (!(r.rows || (r.rows = [])).length) {
          return aux.reject(403, "");
        }
        lc.obj = obj = r.rows[0];
        return io.query("delete from mailverifytoken where owner = $1", [obj.owner]);
      }).then(function(){
        var verified;
        if (new Date().getTime() - new Date(lc.obj.time).getTime() > 1000 * 600) {
          return Promise.reject(new lderror(1013));
        }
        lc.verified = verified = {
          date: Date.now()
        };
        io.query("update users set verified = $2 where key = $1", [lc.obj.owner, JSON.stringify(verified)]);
        if (req.user && req.user.key === lc.obj.owner) {
          req.user.verified = verified;
          return new Promise(function(res, rej){
            req.logIn(req.user, function(){
              return res();
            });
            return null;
          });
        }
      }).then(function(){
        return io.query("select * from users where key = $1", [lc.obj.owner]).then(function(r){
          var u;
          r == null && (r = {});
          if (!(u = (r.rows || (r.rows = []))[0])) {
            return;
          }
          u.verified = lc.verified;
          return io.query("update sessions set detail = jsonb_set(detail, '{passport,user}', ($1)::jsonb)\nwhere (detail->'passport'->'user'->>'key')::int = $2", [JSON.stringify(u), lc.obj.owner]);
        });
      }).then(function(){
        res.redirect('/dash/auth/mail/verify/done/');
        return null;
      })['catch'](function(e){
        if (e instanceof lderror && e.id === 1013) {
          res.redirect('/dash/auth/mail/verify/expire/');
          return null;
        } else {
          return aux.errorHandler(res, true)(e);
        }
      });
    });
  });
}).call(this);
