// Generated by LiveScript 1.3.0
(function(){
  var express;
  express = require('express');
  module.exports = function(engine, io){
    var router;
    router = new express.Router();
    return router;
  };
}).call(this);
