// Generated by LiveScript 1.3.0
(function(){
  var express;
  express = require('express');
  module.exports = function(engine, io){
    return engine.router.ext.post('/deploy', function(req, res){
      return res.send({});
    });
  };
}).call(this);
